version: "3.8"

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/.next
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb

  db:
    image: postgres:13
    container_name: todo-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
